// Additional page copy, educational metadata, and help content.
// Keep the same informal voice and technical vocabulary as GREEK_UI.
export const GREEK_EXTRA: Record<string, string> = {
  "GAMEHACK // SECURE TRAINING ENVIRONMENT": "GAMEHACK // ΑΣΦΑΛΕΣ ΠΕΡΙΒΑΛΛΟΝ ΕΞΑΣΚΗΣΗΣ",
  "PATH": "ΔΙΑΔΡΟΜΗ",
  "LAB": "ΕΡΓΑΣΤΗΡΙΟ",
  "COMPLETE": "ΟΛΟΚΛΗΡΩΘΗΚΕ",
  "IN PROGRESS": "ΣΕ ΕΞΕΛΙΞΗ",
  "objectives": "στόχοι",
  "labs": "εργαστήρια",
  "ranked operators": "παίκτες στην κατάταξη",
  "flags captured": "flags που έχεις βρει",
  "challenges": "προκλήσεις",
  "YOU": "ΕΣΥ",
  "RANK": "ΘΕΣΗ",
  "FLAGS": "ΣΗΜΑΙΕΣ",
  "To rank #": "Για να φτάσεις στη θέση #",
  "member": "μέλος",
  "crews": "ομάδες",
  "Operator": "Παίκτης",
  "Field operative": "Αναλυτής πεδίου",
  "Elite operator": "Έμπειρος αναλυτής",
  "Challenge": "Πρόκληση",
  "Page": "Σελίδα",
  "Learning path": "Εκπαιδευτική διαδρομή",
  "View all": "Προβολή όλων",
  "Save": "Αποθήκευση",
  "BACK TO": "ΕΠΙΣΤΡΟΦΗ ΣΕ",
  "Back to": "Επιστροφή σε",
  "Lab": "Εργαστήριο",
  "Knowledge check": "Έλεγχος γνώσεων",
  "No quiz available": "Δεν υπάρχει διαθέσιμο κουίζ",
  "Full briefing": "Πλήρης ενημέρωση",
  "source challenge": "πρόκληση από εργαστήριο",
  "Linux Foundations": "Βασικές αρχές Linux",
  "Sudo_Run": "Sudo_Run",
  "Linux: The Next Level": "Linux: Επόμενο επίπεδο",
  "Linux: Advanced Ops": "Linux: Προχωρημένες λειτουργίες",
  "Wirewalk": "Wirewalk",
  "Operation Raven": "Επιχείρηση Raven",
  "DFIR Fieldwork": "Πρακτική ψηφιακής εγκληματολογίας",
  "FOUNDATIONS": "ΒΑΣΙΚΕΣ ΑΡΧΕΣ",
  "LINUX BASICS": "ΒΑΣΙΚΑ LINUX",
  "LINUX SYSTEMS": "ΣΥΣΤΗΜΑΤΑ LINUX",
  "RED TEAM OPERATION": "ΕΠΙΧΕΙΡΗΣΗ RED TEAM",
  "BLUE TEAM OPERATION": "ΕΠΙΧΕΙΡΗΣΗ BLUE TEAM",
  "ALL-TIME RANKINGS": "ΚΑΤΑΤΑΞΗ ΟΛΩΝ ΤΩΝ ΕΠΟΧΩΝ",
  "From your first command to root access.": "Από την πρώτη εντολή μέχρι την πρόσβαση root.",
  "Learn Linux by doing, one command at a time.": "Μάθε Linux στην πράξη, μία εντολή τη φορά.",
  "Go deeper into networks, processes and the shell.": "Εξερεύνησε σε βάθος δίκτυα, διεργασίες και το shell.",
  "Script, automate and operate real services.": "Γράψε scripts, αυτοματοποίησε εργασίες και διαχειρίσου υπηρεσίες.",
  "Navigate the SSH labyrinth, one pivot at a time.": "Πέρασε μέσα από τον λαβύρινθο του SSH, βήμα βήμα.",
  "One box. Four flags. A full boot2root experience.": "Ένα μηχάνημα. Τέσσερα flags. Μια ολοκληρωμένη εμπειρία boot2root.",
  "Follow the evidence through a live incident.": "Ακολούθησε τα τεκμήρια και ανασύνθεσε ένα περιστατικό σε εξέλιξη.",
  "Linux CLI": "Γραμμή εντολών Linux (CLI)",
  "Recon": "Αναγνώριση",
  "Networking": "Δικτύωση",
  "Privilege Escalation": "Κλιμάκωση προνομίων",
  "Navigation": "Πλοήγηση",
  "Files": "Αρχεία",
  "Permissions": "Δικαιώματα πρόσβασης",
  "Shell": "Κέλυφος",
  "Processes": "Διεργασίες",
  "Scheduling": "Προγραμματισμένες εργασίες",
  "Environment": "Περιβάλλον",
  "Bash": "Bash",
  "Cron": "Cron",
  "Apache": "Apache",
  "SSH": "SSH",
  "FTP": "FTP",
  "SSH Keys": "Κλειδιά SSH",
  "ProxyJump": "ProxyJump",
  "Pivoting": "Μετακίνηση μεταξύ δικτύων",
  "Tunneling": "Σήραγγες δικτύου",
  "Foothold": "Αρχική πρόσβαση",
  "Root": "Root",
  "Forensics": "Ψηφιακή εγκληματολογία",
  "Incident Response": "Αντιμετώπιση περιστατικών",
  "Malware": "Κακόβουλο λογισμικό",
  "Memory": "Μνήμη",
  "Learning path 06 / 07": "Διαδρομή 06 / 07",
  "% complete": "% ολοκληρώθηκε",
  "A boot2root CTF box. Follow the trail from reconnaissance to root.": "Μια μηχανή CTF τύπου boot2root. Ακολούθησε τα ίχνη από την αναγνώριση μέχρι να αποκτήσεις root.",
  "Next:": "Επόμενο:",
  "PATH 01 / FOUNDATIONS": "ΔΙΑΔΡΟΜΗ 01 / ΘΕΜΕΛΙΑ",
  "The essential skills every operator needs.": "Οι βασικές δεξιότητες που χρειάζεται κάθε παίκτης.",
  "labs · Beginner": "εργαστήρια · Αρχάριο επίπεδο",
  "PATH 07 / BLUE TEAM": "ΔΙΑΔΡΟΜΗ 07 / ΑΜΥΝΑ",
  "Follow the evidence. Find the truth.": "Ακολούθησε τα τεκμήρια. Ανακάλυψε τι συνέβη.",
  "labs · Intermediate": "εργαστήρια · Ενδιάμεσο επίπεδο",
  "+100 XP GOAL": "ΣΤΟΧΟΣ: +100 XP",
  "Today’s progress": "Σημερινή πρόοδος",
  "days": "ημέρες",
  "You": "Εσύ",
  "days completed": "ημέρες σερί",
  "Full rankings": "Πλήρης κατάταξη",
  "A little competition makes everyone better.": "Λίγος ανταγωνισμός μάς βοηθά όλους να γίνουμε καλύτεροι.",
  "Each challenge awards its listed XP once.": "Κάθε πρόκληση αποδίδει τους αναγραφόμενους πόντους XP μία φορά.",
  "Verified objectives earn XP as you train.": "Κερδίζεις XP καθώς ολοκληρώνεις και επαληθεύεις στόχους στα εργαστήρια.",
  "Your cumulative XP determines your place.": "Το σύνολο των XP καθορίζει τη θέση σου στην κατάταξη.",
  "Flags captured": "Flags που έχεις βρει",
  "Total XP": "Συνολικά XP",
  "Total experience": "Συνολικά XP",
  "Among operators": "Ανάμεσα στους παίκτες",
  "Challenges solved": "Λυμένες προκλήσεις",
  "Skills sharpened": "Δεξιότητες που εξάσκησες",
  "Keep earning": "Συνέχισε να κερδίζεις XP",
  "Filter the feed to see your own milestones or the wider community.": "Φίλτραρε τη ροή για να δεις τα δικά σου ορόσημα ή τη δραστηριότητα όλης της κοινότητας.",
  "The best operators never stop learning. Here's the ground you've covered.": "Οι καλύτεροι δεν σταματούν ποτέ να μαθαίνουν. Δες πόσο δρόμο έχεις διανύσει.",
  "UP NEXT": "ΕΠΟΜΕΝΟ",
  "Write the next story.": "Γράψε το επόμενο κεφάλαιο.",
  "Pick a challenge, follow your curiosity, and put your name in the feed.": "Διάλεξε μια πρόκληση, ακολούθησε την περιέργειά σου και μοιράσου την επιτυχία σου στη ροή δραστηριότητας.",
  "Nothing here yet. Your next flag will change that.": "Δεν υπάρχει ακόμη δραστηριότητα. Η επόμενη επιτυχία σου θα εμφανιστεί εδώ.",
  "Every flag brings you closer to your next level.": "Κάθε flag σε φέρνει πιο κοντά στο επόμενο επίπεδο.",
  "Save a challenge to keep it within reach.": "Αποθήκευσε μια πρόκληση για να την έχεις πρόχειρη.",
  "Keep growing.": "Συνέχισε να εξελίσσεσαι.",
  "The next skill is one lab away. Your future self will thank you.": "Ένα εργαστήριο αρκεί για να κάνεις το επόμενο βήμα. Θα χαρείς που ξεκίνησες.",
  "Joined": "Μέλος από",
  "LEVEL": "ΕΠΙΠΕΔΟ",
  "Level": "Επίπεδο",
  "LVL": "ΕΠΙΠ.",
  "OPERATOR // GAMEHACK": "ΠΑΙΚΤΗΣ // GAMEHACK",
  "First Blood": "Πρώτο flag",
  "Shell Initiate": "Πρώτα βήματα στο shell",
  "On a Roll": "Σερί επιτυχιών",
  "Rising Star": "Ανερχόμενο αστέρι",
  "Codebreaker": "Αποκρυπτογράφος",
  "The Investigator": "Ερευνητής",
  "Capture your first flag": "Βρες το πρώτο σου flag",
  "Complete your first lab": "Ολοκλήρωσε το πρώτο σου εργαστήριο",
  "Train for 3 days in a row": "Εξασκήσου για 3 συνεχόμενες ημέρες",
  "Earn 500 total XP": "Συγκέντρωσε συνολικά 500 XP",
  "Solve a crypto challenge": "Λύσε μια πρόκληση κρυπτογραφίας",
  "Solve a forensics case": "Λύσε μια υπόθεση ψηφιακής εγκληματολογίας",
  "A closer look at the disciplines you're exploring.": "Δες σε ποιους τομείς έχεις εξασκηθεί.",
  "The latest chapters of your story.": "Οι πιο πρόσφατες επιτυχίες σου.",
  "Your watchlist of challenges.": "Οι προκλήσεις που έχεις αποθηκεύσει.",
  "of": "από",
  "badges earned": "σήματα που απέκτησες",
  "Connect with other operators and take on the journey together.": "Γνώρισε άλλους παίκτες και ξεκινήστε την πορεία σας μαζί.",
  "Join a crew of curious minds, share the journey, and tackle the arena side by side. The best breakthroughs rarely happen alone.": "Γίνε μέλος μιας ομάδας με ανήσυχο πνεύμα, μοιράσου την εμπειρία και αντιμετωπίστε μαζί τις προκλήσεις. Οι καλύτερες ανακαλύψεις είναι ομαδική υπόθεση.",
  "Ethical practice": "Υπεύθυνη εξάσκηση",
  "Share this code with friends so they can find your crew.": "Μοιράσου αυτόν τον κωδικό με φίλους, για να βρουν την ομάδα σου.",
  "Enter your crew's code and join them in the arena.": "Πληκτρολόγησε τον κωδικό της ομάδας σου και έλα μαζί τους στην αρένα.",
  "Join": "Συμμετοχή",
  "Start a team, get a unique invite code, and bring people together.": "Φτιάξε μια ομάδα, πάρε μοναδικό κωδικό πρόσκλησης και κάλεσε φίλους.",
  "Team name": "Όνομα ομάδας",
  "What's your crew about?": "Πες μας λίγα λόγια για την ομάδα σου.",
  "Create crew": "Δημιουργία ομάδας",
  "Cancel": "Ακύρωση",
  "Find a team that feels like yours.": "Βρες μια ομάδα που σου ταιριάζει.",
  "In another crew": "Σε άλλη ομάδα",
  "Better together.": "Μαζί πετυχαίνουμε περισσότερα.",
  "Team not found. Check the invite code.": "Δεν βρέθηκε ομάδα. Έλεγξε τον κωδικό πρόσκλησης.",
  "Manage your identity and understand how your training data is handled.": "Διαχειρίσου το προφίλ σου και μάθε πώς χρησιμοποιούνται τα δεδομένα εξάσκησής σου.",
  "Gamehack's terminal runs against a fictional virtual filesystem. Commands never touch the server's operating system or any real target.": "Το τερματικό του Gamehack λειτουργεί σε εικονικό σύστημα αρχείων με φανταστικά δεδομένα. Οι εντολές δεν εκτελούνται στο λειτουργικό του διακομιστή ούτε σε πραγματικά συστήματα.",
  "Isolated simulated labs": "Πλήρως απομονωμένα εργαστήρια προσομοίωσης",
  "Progress saved in PostgreSQL": "Η πρόοδός σου αποθηκεύεται στη βάση PostgreSQL",
  "Secure, private account sessions": "Ασφαλείς και ιδιωτικές συνεδρίες λογαριασμού",
  "Quick search": "Γρήγορη αναζήτηση",
  "Find a mission": "Βρες μια αποστολή",
  "Need help getting started?": "Θέλεις βοήθεια για να ξεκινήσεις;",
  "Choose how other operators see you in the arena. Your profile is yours to shape.": "Διάλεξε πώς θα εμφανίζεται το προφίλ σου στους άλλους παίκτες. Εσύ αποφασίζεις πώς θα το διαμορφώσεις.",
  "Jump straight into the arena.": "Μπες κατευθείαν στην αρένα.",
  "Login and registration are temporarily disabled. No account is needed to explore challenges, practice in labs, or join a team.": "Προς το παρόν, δεν είναι διαθέσιμη η σύνδεση ή η εγγραφή. Μπορείς να δοκιμάσεις τις προκλήσεις και τα εργαστήρια ή να μπεις σε ομάδα χωρίς λογαριασμό.",
  "Your progress is saved automatically to this browser session. Keep your browser data to retain access to it.": "Η πρόοδός σου αποθηκεύεται αυτόματα σε αυτή τη συνεδρία του browser. Μην καθαρίσεις τα δεδομένα περιήγησης, για να μη χάσεις την πρόσβασή σου.",
  "Go to dashboard": "Πήγαινε στην αρχική",
  "Your account is secured.": "Ο λογαριασμός σου είναι προστατευμένος.",

  "Email address": "Διεύθυνση email",
  "Signed in as": "Συνδεδεμένος ως",
  "Make your progress yours.": "Κράτησε την πρόοδό σου στον λογαριασμό σου.",
  "You're exploring as a guest. Create an account to keep your flags, XP and lab progress linked to you.": "Χρησιμοποιείς την πλατφόρμα ως επισκέπτης. Δημιούργησε λογαριασμό για να συνδέσεις μαζί του τα flags, τα XP και την πρόοδό σου στα εργαστήρια.",
  "Create account": "Δημιουργία λογαριασμού",
  "Sign in": "Σύνδεση",
  "Password": "Κωδικός",
  "Your password is securely hashed. Your lab activity stays in a safe simulation.": "Ο κωδικός σου αποθηκεύεται με μη αναστρέψιμο κατακερματισμό (hash). Η δραστηριότητά σου στα εργαστήρια παραμένει σε ασφαλή προσομοίωση.",
  "New to the arena? Here's what you need to know to get moving.": "Πρώτη φορά στην αρένα; Δες πώς να ξεκινήσεις.",
  "THE GAMEHACK FIELD MANUAL": "Ο ΟΔΗΓΟΣ ΠΕΔΙΟΥ GAMEHACK",
  "Gamehack is built for curious minds at every level. Everything here is designed for learning in a safe, ethical environment.": "Το Gamehack απευθύνεται σε ανθρώπους με περιέργεια, ανεξάρτητα από το επίπεδό τους. Όλα εδώ έχουν σχεδιαστεί για ασφαλή και υπεύθυνη μάθηση.",
  "Investigate a standalone challenge, decode the clues, and submit your answer.": "Διερεύνησε μια αυτόνομη πρόκληση, εξέτασε τα στοιχεία και υπέβαλε την απάντησή σου.",
  "Browse challenges": "Περιήγηση προκλήσεων",
  "Follow a guided learning path and practice commands in the safe simulator.": "Ακολούθησε μια εκπαιδευτική διαδρομή και δοκίμασε εντολές σε ασφαλή προσομοίωση.",
  "Explore paths": "Εξερεύνησε διαδρομές",
  "Join a team, compare notes, and stay motivated with other operators.": "Γίνε μέλος μιας ομάδας, αντάλλαξε ιδέες και κράτα το κίνητρο ψηλά μαζί με άλλους παίκτες.",
  "Visit Team Hub": "Δες τις ομάδες",
  "Use these skills to understand and protect systems. Gamehack's challenges and labs are fictional, authorized spaces to practice. Never test systems without permission.": "Χρησιμοποίησε αυτές τις δεξιότητες για να κατανοείς και να προστατεύεις συστήματα. Οι προκλήσεις και τα εργαστήρια του Gamehack είναι φανταστικά περιβάλλοντα εξάσκησης. Μην δοκιμάζεις ποτέ συστήματα χωρίς άδεια.",
  "Train ethically. Think differently. Build responsibly.": "Μάθε υπεύθυνα. Σκέψου διαφορετικά. Δημιούργησε με υπευθυνότητα.",
  "QUICK TIP": "ΓΡΗΓΟΡΗ ΣΥΜΒΟΥΛΗ",
  "In a lab, type": "Στο εργαστήριο, γράψε",
  "to see commands or": "για να δεις τις διαθέσιμες εντολές ή",
  "for a manual page. Curiosity is your best tool.": "για να ανοίξεις τον οδηγό της εντολής. Η περιέργεια είναι το καλύτερο εργαλείο σου.",
  "What is Gamehack?": "Τι είναι το Gamehack;",
  "Gamehack is a hands-on cybersecurity learning platform. Solve self-contained CTF challenges, practice in guided labs, earn XP, and grow your skills at your own pace.": "Το Gamehack είναι μια πλατφόρμα πρακτικής εκπαίδευσης στην κυβερνοασφάλεια. Λύσε αυτόνομες προκλήσεις CTF, εξασκήσου σε οργανωμένα εργαστήρια, κέρδισε XP και προχώρα με τον δικό σου ρυθμό.",
  "How do I solve a challenge?": "Πώς λύνω μια πρόκληση;",
  "Open a challenge, read the mission briefing, and inspect the evidence artifact. Follow the clues until you find a flag in the format GAMEHACK{...}. Submit the complete flag in the mission panel. Hints are available if you get stuck.": "Άνοιξε μια πρόκληση, διάβασε την περιγραφή της αποστολής και εξέτασε το αρχείο με τα στοιχεία. Ακολούθησε τα ίχνη μέχρι να βρεις ένα flag της μορφής GAMEHACK{...} και υπέβαλε ολόκληρο το flag από το πλαίσιο της αποστολής. Αν κολλήσεις, μπορείς να δεις υποδείξεις.",
  "Are the terminal labs safe?": "Είναι ασφαλή τα εργαστήρια τερματικού;",
  "Yes. The terminal is a simulated Linux environment with fictional files, hosts, and processes. Commands are interpreted inside the browser and verified against the simulation. Nothing runs on a real host or network.": "Ναι. Το τερματικό προσομοιώνει Linux με φανταστικά αρχεία, υπολογιστές (hosts) και διεργασίες. Οι εντολές εκτελούνται μέσα στον browser και ελέγχονται από την προσομοίωση. Δεν εκτελείται τίποτα σε πραγματικό υπολογιστή ή δίκτυο.",
  "How do I earn XP?": "Πώς κερδίζω XP;",
  "Capture a challenge flag to earn its listed XP once. In learning paths, completing verified lab objectives and finishing a lab also awards XP. Your total XP determines your level and leaderboard position.": "Βρες το flag μιας πρόκλησης για να κερδίσεις τους αντίστοιχους XP — μία φορά ανά πρόκληση. Στις εκπαιδευτικές διαδρομές, κερδίζεις XP ολοκληρώνοντας επαληθευμένους στόχους και εργαστήρια. Τα συνολικά XP καθορίζουν το επίπεδο και τη θέση σου στην κατάταξη.",
  "Will my progress be saved?": "Θα αποθηκευτεί η πρόοδός μου;",
  "Yes. Your flags, XP, lab objectives, profile, and team membership are saved automatically to your guest session. Login and registration are temporarily disabled; keep your browser data to retain access to this progress.": "Ναι. Τα flags, τα XP, οι στόχοι των εργαστηρίων, το προφίλ και η συμμετοχή σου σε ομάδα αποθηκεύονται αυτόματα στη συνεδρία επισκέπτη. Προς το παρόν, η σύνδεση και η εγγραφή δεν είναι διαθέσιμες· μην καθαρίσεις τα δεδομένα του browser, για να διατηρήσεις την πρόσβαση στην πρόοδό σου.",
  "Can I use hints?": "Μπορώ να χρησιμοποιήσω υποδείξεις;",
  "Absolutely. Hints are part of learning, not a shortcut to be ashamed of. Reveal one at a time and try to understand why the answer works.": "Φυσικά. Οι υποδείξεις είναι μέρος της μάθησης — δεν υπάρχει λόγος να ντρέπεσαι που τις χρησιμοποιείς. Δες τες μία μία και προσπάθησε να καταλάβεις γιατί λειτουργεί η λύση.",
  "How do teams work?": "Πώς λειτουργούν οι ομάδες;",
  "Visit Team Hub to join an open community crew, enter a friend's invite code, or create your own team. You can leave a team and join a different one whenever you like.": "Στην ενότητα «Ομάδες» μπορείς να μπεις σε μια ανοιχτή ομάδα, να χρησιμοποιήσεις τον κωδικό πρόσκλησης ενός φίλου ή να δημιουργήσεις τη δική σου. Μπορείς να αποχωρήσεις και να αλλάξεις ομάδα όποτε θέλεις.",
  "Your progress is linked to your email address.": "Η πρόοδός σου συνδέεται με τον λογαριασμό Gamehack σου.",
  "Yes. Your flags, XP, lab objectives, profile, and team membership are saved to your account. Start as a guest, then create an account to keep that progress. No email is needed; save the private key file generated at signup for password-free recovery.": "Ναι. Τα flags, τα XP, οι στόχοι των εργαστηρίων, το προφίλ και η συμμετοχή σου σε ομάδα αποθηκεύονται στον λογαριασμό σου. Ξεκίνα ως επισκέπτης και δημιούργησε λογαριασμό για να διατηρήσεις την πρόοδό σου. Δεν χρειάζεται email· φύλαξε το ιδιωτικό αρχείο κλειδιού που δημιουργείται στην εγγραφή για σύνδεση χωρίς κωδικό.",
  "Your progress is on this device.": "Η πρόοδός σου βρίσκεται σε αυτή τη συσκευή.",
  "Create an account to keep your progress, or sign in to an existing account.": "Δημιούργησε λογαριασμό για να διατηρήσεις την πρόοδό σου ή συνδέσου σε έναν υπάρχοντα λογαριασμό.",
  "Signed in with your Gamehack handle. No email is required.": "Έχεις συνδεθεί με το όνομα χρήστη Gamehack σου. Δεν χρειάζεται email.",
  "Password and recovery-key settings": "Ρυθμίσεις κωδικού και κλειδιού ανάκτησης",
  "Protect your progress.": "Προστάτεψε την πρόοδό σου.",
  "Create an account to set a password and download an account-specific recovery key file.": "Δημιούργησε λογαριασμό για να ορίσεις κωδικό και να κατεβάσεις το προσωπικό αρχείο κλειδιού ανάκτησης.",
  "Password and recovery": "Κωδικός και ανάκτηση",
  "Account security for": "Ασφάλεια λογαριασμού για",
  "Password-free sign-in file": "Αρχείο σύνδεσης χωρίς κωδικό",
  "The key file is tied to this account. Anyone with the file can sign in, so store it somewhere private. Creating a new one immediately revokes the old file.": "Το αρχείο κλειδιού συνδέεται με αυτόν τον λογαριασμό. Όποιος το έχει μπορεί να συνδεθεί, γι’ αυτό φύλαξέ το σε ιδιωτικό μέρος. Η δημιουργία νέου αρχείου ακυρώνει αμέσως το παλιό.",
  "No email recovery is available yet. Keep your password and key file safe.": "Δεν υπάρχει ακόμη ανάκτηση μέσω email. Φύλαξε με ασφάλεια τον κωδικό και το αρχείο κλειδιού σου.",
  "Use your current password to set a new one. Your other active sessions will be signed out.": "Χρησιμοποίησε τον τρέχοντα κωδικό για να ορίσεις νέο. Οι υπόλοιπες ενεργές συνεδρίες σου θα αποσυνδεθούν.",
  "Preparing file...": "Προετοιμασία αρχείου...",
  "Generate and download a new key file": "Δημιουργία και λήψη νέου αρχείου κλειδιού",
  "Current password": "Τρέχων κωδικός",
  "New password": "Νέος κωδικός",
  "Confirm new password": "Επιβεβαίωση νέου κωδικού",
  "Confirm password": "Επιβεβαίωση κωδικού",
  "Update password": "Ενημέρωση κωδικού",
  "Updating...": "Ενημέρωση...",
  "The new passwords do not match.": "Οι νέοι κωδικοί δεν ταιριάζουν.",
  "Sign in to a registered account to change its password.": "Συνδέσου σε λογαριασμό για να αλλάξεις τον κωδικό του.",
  "The new password must be between 8 and 128 characters.": "Ο νέος κωδικός πρέπει να έχει από 8 έως 128 χαρακτήρες.",
  "Your current password is incorrect.": "Ο τρέχων κωδικός δεν είναι σωστός.",
  "Choose a password you have not used for this account.": "Διάλεξε κωδικό που δεν έχεις χρησιμοποιήσει ξανά σε αυτόν τον λογαριασμό.",
  "Your password has been updated.": "Ο κωδικός σου ενημερώθηκε.",
  "Connection error. Please try again.": "Πρόβλημα σύνδεσης. Δοκίμασε ξανά.",
  "Create a new account key file? Any older key file will stop working.": "Να δημιουργηθεί νέο αρχείο κλειδιού; Κάθε παλιότερο αρχείο θα πάψει να λειτουργεί.",
  "Sign in to an account before creating a recovery key.": "Συνδέσου σε λογαριασμό πριν δημιουργήσεις κλειδί ανάκτησης.",
  "Unable to create the account key file.": "Δεν ήταν δυνατή η δημιουργία του αρχείου κλειδιού.",
  "A new account key file was downloaded. Keep it private; the previous file has been revoked.": "Κατέβηκε νέο αρχείο κλειδιού. Φύλαξέ το ιδιωτικά· το προηγούμενο αρχείο έχει ακυρωθεί.",
  "How should we call you?": "Πώς να σε αποκαλούμε;",
  "At least 8 characters": "Τουλάχιστον 8 χαρακτήρες",
  "Enter your password again": "Πληκτρολόγησε ξανά τον κωδικό σου",
  "Your handle, e.g. alex_morgan": "Το όνομα χρήστη σου, π.χ. alex_morgan",
  "Your password": "Ο κωδικός σου",
  "Choose account key file": "Επίλεξε αρχείο κλειδιού λογαριασμού",
  "Choose Gamehack account key file": "Επίλεξε το αρχείο κλειδιού λογαριασμού Gamehack",
  "Choose a sign-in method": "Επίλεξε τρόπο σύνδεσης",
  "Choose your Gamehack account key file.": "Επίλεξε το αρχείο κλειδιού λογαριασμού Gamehack.",
  "That file is too large to be a Gamehack account key.": "Το αρχείο είναι υπερβολικά μεγάλο για να είναι κλειδί λογαριασμού Gamehack.",
  "Incorrect handle/email or password.": "Το όνομα χρήστη/email ή ο κωδικός είναι λανθασμένα.",
  "This account key is invalid or has been replaced.": "Αυτό το κλειδί λογαριασμού είναι άκυρο ή έχει αντικατασταθεί.",
  "Unable to sign in. Check your details and try again.": "Δεν ήταν δυνατή η σύνδεση. Έλεγξε τα στοιχεία σου και δοκίμασε ξανά.",
  "Enter a name with at least 2 characters.": "Πληκτρολόγησε όνομα με τουλάχιστον 2 χαρακτήρες.",
  "Password must be between 8 and 128 characters.": "Ο κωδικός πρέπει να έχει από 8 έως 128 χαρακτήρες.",
  "Enter your handle or email and a valid password.": "Πληκτρολόγησε το όνομα χρήστη ή το email σου και έναν έγκυρο κωδικό.",
  "Choose a valid Gamehack account key file.": "Επίλεξε έγκυρο αρχείο κλειδιού λογαριασμού Gamehack.",
  "That file is not a valid Gamehack account key.": "Αυτό το αρχείο δεν είναι έγκυρο κλειδί λογαριασμού Gamehack.",
  "Unable to complete that request. Please try again.": "Δεν ήταν δυνατή η ολοκλήρωση του αιτήματος. Δοκίμασε ξανά.",
  "The passwords do not match.": "Οι κωδικοί δεν ταιριάζουν.",
  "Unable to create your account.": "Δεν ήταν δυνατή η δημιουργία του λογαριασμού σου.",
  "You are already signed in.": "Έχεις ήδη συνδεθεί.",
  "That request is too large.": "Το αίτημα είναι υπερβολικά μεγάλο.",
  "Enter your name with at least 2 characters.": "Πληκτρολόγησε όνομα με τουλάχιστον 2 χαρακτήρες.",

};
