import type { Bi } from "@/data/lessons";
import { GREEK_EXTRA } from "@/lib/extraGreek";

export type Lang = "en" | "el";
export const LANGUAGE_COOKIE = "gamehack_lang";

// UI copy is keyed by its English string so server- and client-rendered views use
// the same translation. Greek copy follows a conversational, informal tone and keeps
// common CTF terms such as flag and XP when that is clearer than a literal translation.
export const GREEK_UI: Record<string, string> = {
  "COMMAND CENTER": "ΚΕΝΤΡΟ ΕΛΕΓΧΟΥ",
  "COMMUNITY": "ΚΟΙΝΟΤΗΤΑ",
  "YOUR ACCOUNT": "Ο ΛΟΓΑΡΙΑΣΜΟΣ ΣΟΥ",
  "Dashboard": "Αρχική",
  "Challenges": "Προκλήσεις",
  "Learning Paths": "Εκπαιδευτικές διαδρομές",
  "Leaderboard": "Κατάταξη",
  "Team Hub": "Ομάδες",
  "Activity Feed": "Ροή δραστηριότητας",
  "My Profile": "Το προφίλ μου",
  "Settings": "Ρυθμίσεις",
  "Help & Support": "Βοήθεια και υποστήριξη",
  "Workspace": "Χώρος εργασίας",
  "CYBER RANGE PLATFORM": "ΠΕΡΙΒΑΛΛΟΝ ΕΚΠΑΙΔΕΥΣΗΣ ΚΥΒΕΡΝΟΑΣΦΑΛΕΙΑΣ",
  "ALL SYSTEMS OPERATIONAL": "ΟΛΑ ΤΑ ΣΥΣΤΗΜΑΤΑ ΛΕΙΤΟΥΡΓΟΥΝ",
  "OPERATOR ONLINE": "ΠΑΙΚΤΗΣ ΣΕ ΣΥΝΔΕΣΗ",
  "Level up your skills.": "Ανέβασε επίπεδο.",
  "Real challenges. Real progress. A safe place to become exceptional.": "Ουσιαστικές προκλήσεις. Αληθινή πρόοδος. Ένα ασφαλές περιβάλλον για να ξεχωρίσεις.",
  "Explore the academy": "Εξερεύνησε την ακαδημία",
  "Search anything...": "Αναζήτησε οτιδήποτε...",
  "Notifications": "Ειδοποιήσεις",
  "Recent activity": "Πρόσφατη δραστηριότητα",
  "View all activity": "Δες όλη τη δραστηριότητα",
  "Account settings": "Ρυθμίσεις λογαριασμού",
  "Guest access active": "Πρόσβαση επισκέπτη ενεργή",
  "Sign out": "Αποσύνδεση",
  "Save your progress": "Αποθήκευσε την πρόοδό σου",
  "No results found. Try another search.": "Δεν βρέθηκαν αποτελέσματα. Δοκίμασε με άλλους όρους.",
  "Search challenges, paths, or pages...": "Αναζήτησε προκλήσεις, διαδρομές ή σελίδες...",
  "Quick access": "Γρήγορη πρόσβαση",
  "Search results": "Αποτελέσματα αναζήτησης",
  "to navigate": "για πλοήγηση",
  "to open": "για άνοιγμα",
  "to close": "για κλείσιμο",
  "Sandbox environment · No real systems exposed": "Περιβάλλον προσομοίωσης · Δεν επηρεάζονται πραγματικά συστήματα",
  "Train ethically. Think differently.": "Εξασκήσου υπεύθυνα. Σκέψου διαφορετικά.",
  "COMMAND CENTER / OVERVIEW": "ΚΕΝΤΡΟ ΕΛΕΓΧΟΥ / ΕΠΙΣΚΟΠΗΣΗ",
  "Welcome back,": "Καλώς επέστρεψες,",
  "Your arena is ready. Pick up where you left off, or take on something new.": "Η αρένα σε περιμένει. Συνέχισε από εκεί που σταμάτησες ή δοκίμασε κάτι καινούριο.",
  "THE ARENA IS YOURS": "Η ΑΡΕΝΑ ΕΙΝΑΙ ΔΙΚΗ ΣΟΥ",
  "Think like a hacker.": "Σκέψου σαν χάκερ.",
  "Train like a pro.": "Εξασκήσου σαν επαγγελματίας.",
  "Solve real-world inspired challenges, master new skills in a safe lab, and climb the ranks. Your next breakthrough starts here.": "Λύσε προκλήσεις εμπνευσμένες από πραγματικά περιστατικά, μάθε νέες δεξιότητες σε ασφαλή εργαστήρια και ανέβα στην κατάταξη. Η επόμενη μεγάλη σου ανακάλυψη ξεκινά εδώ.",
  "Explore challenges": "Εξερεύνησε προκλήσεις",
  "Resume training": "Συνέχισε την εξάσκηση",
  "Total experience": "Συνολικά XP",
  "XP earned in the arena": "XP που κέρδισες στην αρένα",
  "Global rank": "Παγκόσμια κατάταξη",
  "Among active operators": "Ανάμεσα στους ενεργούς παίκτες",
  "Flags captured": "Flags που έχεις βρει",
  "Across all categories": "Σε όλες τις κατηγορίες",
  "Training streak": "Σερί εξάσκησης",
  "Continue your journey": "Συνέχισε την πορεία σου",
  "Get back into the lab and keep your momentum going.": "Μπες ξανά στο εργαστήριο και συνέχισε από εκεί που σταμάτησες.",
  "All learning paths": "Όλες οι διαδρομές",
  "Recommended challenges": "Προτεινόμενες προκλήσεις",
  "Handpicked missions to push your skills further.": "Επιλεγμένες αποστολές για να πας τις δεξιότητές σου ένα βήμα παραπέρα.",
  "Browse all challenges": "Δες όλες τις προκλήσεις",
  "Explore learning paths": "Δες τις εκπαιδευτικές διαδρομές",
  "Structured training, from the first command to advanced defense.": "Βήμα-βήμα εξάσκηση: από τις πρώτες εντολές μέχρι την προχωρημένη άμυνα.",
  "View academy": "Προβολή ακαδημίας",
  "Daily objective": "Ημερήσιος στόχος",
  "A little progress, every single day.": "Λίγο-λίγο, κάθε μέρα.",
  "One flag a day.": "Ένα flag την ημέρα.",
  "Small wins build serious skills. Capture one flag today to keep the momentum.": "Κάθε μικρή νίκη σε βοηθά να γίνεις καλύτερος. Βρες σήμερα ένα flag και κράτα το σερί σου.",
  "Today's progress": "Σημερινή πρόοδος",
  "Find a challenge": "Διάλεξε μια πρόκληση",
  "Explore more challenges": "Δες κι άλλες προκλήσεις",
  "Top operators": "Κορυφαίοι παίκτες",
  "The minds making moves this season.": "Οι παίκτες που ξεχωρίζουν αυτή τη σεζόν.",
  "Full rankings": "Πλήρης κατάταξη",
  "Live activity": "Ζωντανή δραστηριότητα",
  "What's happening across the arena.": "Όσα συμβαίνουν στην αρένα.",
  "View feed": "Δες τη ροή δραστηριότητας",
  "New to the arena?": "Πρώτη φορά στην αρένα;",
  "Learn how Gamehack works": "Μάθε πώς λειτουργεί το Gamehack",
  "Continue operation": "Συνέχισε την αποστολή",
  "FEATURED OPERATION": "ΠΡΟΤΕΙΝΟΜΕΝΗ ΑΠΟΣΤΟΛΗ",
  "Complete": "Ολοκληρώθηκε",
  "completed": "ολοκληρώθηκαν",
  "solves": "λύσεις",
  "days": "ημέρες",
  "day": "ημέρα",
  "labs completed": "ολοκληρωμένα εργαστήρια",
  "OPERATOR": "ΠΑΙΚΤΗΣ",
  "TOTAL XP": "ΣΥΝΟΛΙΚΑ XP",
  "THE ARENA / CHALLENGES": "Η ΑΡΕΝΑ / ΠΡΟΚΛΗΣΕΙΣ",
  "Every flag tells a story": "Κάθε flag έχει τη δική του ιστορία.",
  "Think critically. Dig deeper. Learn something new with every solve.": "Σκέψου κριτικά. Ψάξε πιο βαθιά. Μάθε κάτι καινούριο με κάθε πρόκληση.",
  "FLAGS CAPTURED": "FLAGS ΠΟΥ ΒΡΗΚΕΣ",
  "FEATURED CHALLENGE": "ΠΡΟΤΕΙΝΟΜΕΝΗ ΠΡΟΚΛΗΣΗ",
  "Follow the clues, decode the evidence, and claim your place on the board.": "Ακολούθησε τα ίχνη, αποκωδικοποίησε τα δεδομένα και διεκδίκησε μια θέση στην κατάταξη.",
  "Accept challenge": "Ξεκίνα την πρόκληση",
  "Find a challenge that meets you where you are, then push beyond it.": "Διάλεξε μια πρόκληση στα μέτρα σου — και δες μέχρι πού μπορείς να φτάσεις.",
  "All challenges": "Όλες οι προκλήσεις",
  "Source labs": "Εργαστήρια διαδρομών",
  "Standalone CTF": "Αυτόνομες προκλήσεις CTF",
  "All levels": "Όλα τα επίπεδα",
  "Recommended": "Προτεινόμενες",
  "Highest XP": "Περισσότερα XP",
  "Lowest XP": "Λιγότερα XP",
  "Most solved": "Περισσότερες λύσεις",
  "Unsolved": "Άλυτες",
  "Saved": "Αποθηκευμένες",
  "Showing": "Προβάλλονται",
  "Curated for ethical practice": "Επιλεγμένες για υπεύθυνη εξάσκηση",
  "No challenges found": "Δεν βρέθηκαν προκλήσεις",
  "Try a different search or clear a filter to uncover more missions.": "Δοκίμασε άλλη αναζήτηση ή αφαίρεσε κάποιο φίλτρο για να δεις περισσότερες αποστολές.",
  "Clear all filters": "Κατάργηση όλων των φίλτρων",
  "Search by name, skill, or topic...": "Αναζήτησε με τίτλο, δεξιότητα ή θέμα...",
  "Open lab": "Μπες στο εργαστήριο",
  "Completed": "Ολοκληρώθηκε",
  "In progress": "Σε εξέλιξη",
  "Locked": "Κλειδωμένο",
  "SOLVED": "ΛΥΘΗΚΕ",
  "CAPTURED": "ΒΡΕΘΗΚΕ",
  "Source challenge": "Πρόκληση από εργαστήριο",
  "Lab objective": "Στόχος εργαστηρίου",
  "missions cleared": "ολοκληρωμένες αποστολές",
  "Original Gamehack labs": "Εργαστήρια της αρχικής διαδρομής Gamehack",
  "new standalone missions": "νέες αυτόνομες αποστολές",
  "Back to challenges": "Επιστροφή στις προκλήσεις",
  "Mission briefing": "Περιγραφή αποστολής",
  "The situation": "Η κατάσταση",
  "Your objective": "Ο στόχος σου",
  "Evidence locker": "Φάκελος τεκμηρίων",
  "Inspect the supplied artifact. Everything you need is here.": "Εξέτασε το αρχείο που παρέχεται. Ό,τι χρειάζεσαι βρίσκεται εδώ.",
  "Copy": "Αντιγραφή",
  "Copied!": "Αντιγράφηκε!",
  "Download": "Λήψη",
  "READ ONLY": "ΜΟΝΟ ΓΙΑ ΑΝΑΓΝΩΣΗ",
  "Safe, fictional training artifact · No external systems involved": "Ασφαλές, φανταστικό αρχείο εξάσκησης · Δεν γίνεται σύνδεση σε πραγματικά συστήματα",
  "Need a nudge?": "Θες μια υπόδειξη;",
  "Hints are here when you need them. Try finding your own way first.": "Αν κολλήσεις, άνοιξε μια υπόδειξη. Πρώτα δοκίμασε να βρεις τη λύση μόνος σου.",
  "Reveal hint": "Δες την υπόδειξη",
  "Hide hint": "Κρύψε την υπόδειξη",
  "Capture the flag": "Βρες το flag",
  "Got the answer? Submit it to claim your points and mark this mission complete.": "Βρήκες την απάντηση; Υπέβαλε το flag για να κερδίσεις πόντους και να ολοκληρώσεις την αποστολή.",
  "Flag submission": "Υποβολή flag",
  "Flags are case-sensitive. Include the curly braces.": "Τα κεφαλαία και τα πεζά έχουν σημασία. Συμπερίλαβε και τα άγκιστρα {}.",
  "Submit flag": "Υποβολή flag",
  "Submit another answer": "Δοκίμασε ξανά",
  "Checking flag...": "Έλεγχος flag...",
  "Mission intel": "Στοιχεία αποστολής",
  "Category": "Κατηγορία",
  "Difficulty": "Δυσκολία",
  "Reward": "Ανταμοιβή",
  "Estimated time": "Εκτιμώμενη διάρκεια",
  "You've already captured this flag.": "Έχεις ήδη βρει αυτό το flag.",
  "Beginner": "Αρχάριο",
  "Easy": "Εύκολο",
  "Medium": "Μεσαίο",
  "Hard": "Δύσκολο",
  "Advanced": "Προχωρημένο",
  "Intermediate": "Ενδιάμεσο",
  "Web Exploitation": "Εκμετάλλευση εφαρμογών ιστού",
  "Cryptography": "Κρυπτογραφία",
  "Digital Forensics": "Ψηφιακή εγκληματολογία",
  "OSINT": "Έρευνα ανοικτών πηγών",
  "Reverse Engineering": "Αντίστροφη μηχανική",
  "Linux": "Linux",
  "Network Security": "Ασφάλεια δικτύων",
  "Back to the arena": "Επιστροφή στην αρένα",
  "THE ACADEMY / LEARNING PATHS": "Η ΑΚΑΔΗΜΙΑ / ΕΚΠΑΙΔΕΥΤΙΚΕΣ ΔΙΑΔΡΟΜΕΣ",
  "Build skills that stick": "Απόκτησε δεξιότητες που μένουν",
  "A guided journey from your first terminal command to complex security operations.": "Μια οργανωμένη πορεία: από την πρώτη εντολή στο τερματικό μέχρι σύνθετες αποστολές κυβερνοασφάλειας.",
  "Labs cleared": "Εργαστήρια που ολοκλήρωσες",
  "Labs available": "Διαθέσιμα εργαστήρια",
  "HANDS-ON CYBER TRAINING": "ΠΡΑΚΤΙΚΗ ΕΚΠΑΙΔΕΥΣΗ ΣΤΗΝ ΚΥΒΕΡΝΟΑΣΦΑΛΕΙΑ",
  "Don't just read about security.": "Μη μείνεις στη θεωρία της ασφάλειας.",
  "Get your hands on it.": "Πέρνα από τη θεωρία στην πράξη.",
  "Every path is made of interactive labs with a persistent, simulated Linux environment. Practice the process, not just the answer. No real systems are touched.": "Κάθε διαδρομή περιλαμβάνει διαδραστικά εργαστήρια σε ένα προσομοιωμένο περιβάλλον Linux που διατηρεί την πρόοδό σου. Μάθε τη διαδικασία, όχι μόνο τη σωστή απάντηση. Δεν επηρεάζεται κανένα πραγματικό σύστημα.",
  "guided paths": "καθοδηγούμενες διαδρομές",
  "interactive labs": "διαδραστικά εργαστήρια",
  "Safe sandbox": "Ασφαλές περιβάλλον εξάσκησης",
  "Choose your path": "Διάλεξε διαδρομή",
  "Start anywhere. Progress at your own pace.": "Ξεκίνα από όπου θέλεις και προχώρα με τον δικό σου ρυθμό.",
  "paths available": "διαθέσιμες διαδρομές",
  "Start path": "Ξεκίνα τη διαδρομή",
  "Continue path": "Συνέχισε τη διαδρομή",
  "Start learning": "Ξεκίνα την εκπαίδευσή σου",
  "Continue learning": "Συνέχισε την εκπαίδευσή σου",
  "Your mission roadmap": "Ο χάρτης πορείας σου",
  "Work through each lab to unlock the next stage.": "Ολοκλήρωσε κάθε εργαστήριο για να ξεκλειδώσεις το επόμενο στάδιο.",
  "Your progress": "Η πρόοδός σου",
  "Keep the momentum going.": "Μην χάνεις τον ρυθμό σου.",
  "Your journey starts here.": "Η πορεία σου ξεκινά εδώ.",
  "Resume next lab": "Συνέχισε στο επόμενο εργαστήριο",
  "Begin first lab": "Ξεκίνα το πρώτο εργαστήριο",
  "Skills you'll build": "Τι θα μάθεις",
  "Complete objectives and challenges to earn XP and advance your operator rank.": "Ολοκλήρωσε στόχους και προκλήσεις, κέρδισε XP και ανέβα στην κατάταξη.",
  "A safe place to experiment": "Ασφαλές περιβάλλον για πειραματισμό",
  "Every command runs in a fictional local simulation. No live targets or host systems are affected.": "Οι εντολές εκτελούνται σε φανταστική, τοπική προσομοίωση. Δεν επηρεάζεται κανένα πραγματικό σύστημα ή στόχος.",
  "hands-on labs": "πρακτικά εργαστήρια",
  "Learning path": "Εκπαιδευτική διαδρομή",
  "Coming up": "Στη συνέχεια",
  "Lab workspace": "Εργαστήριο",
  "Briefing": "Περιγραφή αποστολής",
  "Command guide": "Οδηγός εντολών",
  "Knowledge check": "Τεστ γνώσεων",
  "Your mission progress": "Η πρόοδός σου στην αποστολή",
  "Complete objectives in the terminal to earn XP.": "Ολοκλήρωσε τους στόχους στο τερματικό και κέρδισε XP.",
  "SIMULATED LAB ACTIVE": "ΤΟ ΠΡΟΣΟΜΟΙΩΜΕΝΟ ΕΡΓΑΣΤΗΡΙΟ ΛΕΙΤΟΥΡΓΕΙ",
  "LAB COMPLETED": "ΤΟ ΕΡΓΑΣΤΗΡΙΟ ΟΛΟΚΛΗΡΩΘΗΚΕ",
  "XP AVAILABLE": "ΔΙΑΘΕΣΙΜΑ XP",
  "Initializing sandbox...": "Προετοιμάζουμε το εργαστήριο...",
  "Terminal cleared. Type help to get started.": "Καθαρίστηκε η οθόνη του τερματικού. Γράψε help για να ξεκινήσεις.",
  "Booting isolated training environment...": "Εκκίνηση απομονωμένου περιβάλλοντος εξάσκησης...",
  "Type a command...": "Πληκτρολόγησε μια εντολή...",
  "Virtual filesystem · No real commands are executed": "Εικονικό σύστημα αρχείων · Οι εντολές δεν εκτελούνται σε πραγματικό σύστημα",
  "Syncing progress...": "Αποθήκευση προόδου...",
  "Progress synced": "Η πρόοδός σου αποθηκεύτηκε",
  "Quick start": "Γρήγορη εκκίνηση",
  "Click a command to run it": "Κάνε κλικ σε μια εντολή για να την εκτελέσεις",
  "MISSION CONTEXT": "ΠΛΑΙΣΙΟ ΑΠΟΣΤΟΛΗΣ",
  "Before you begin": "Πριν ξεκινήσεις",
  "FIELD REFERENCE": "ΣΥΝΤΟΜΟΣ ΟΔΗΓΟΣ",
  "Commands worth knowing": "Εντολές που αξίζει να ξέρεις",
  "Study the syntax, then try it for yourself in the workspace.": "Δες τη σύνταξη και δοκίμασε την εντολή στον χώρο εργασίας.",
  "Mission objectives": "Στόχοι αποστολής",
  "Complete these in the terminal.": "Ολοκλήρωσέ τους στο τερματικό.",
  "Show hint": "Δες υπόδειξη",
  "BONUS CHALLENGE": "ΕΠΙΠΛΕΟΝ ΠΡΟΚΛΗΣΗ",
  "Objectives are verified against your simulated lab activity.": "Η ολοκλήρωση των στόχων ελέγχεται μέσα από τη δραστηριότητά σου στο προσομοιωμένο εργαστήριο.",
  "Mission complete.": "Η αποστολή ολοκληρώθηκε.",
  "You've mastered this stage. Your XP and progress are saved.": "Ολοκλήρωσες αυτό το στάδιο. Τα XP και η πρόοδός σου αποθηκεύτηκαν.",
  "Next lab": "Επόμενο εργαστήριο",
  "View path": "Προβολή διαδρομής",
  "Stuck on a command?": "Κόλλησες σε μια εντολή;",
  "Open command guide": "Άνοιξε τον οδηγό εντολών",
  "Reset sandbox": "Επαναφορά προσομοίωσης",
  "Why this matters": "Γιατί έχει σημασία",
  "What to look for": "Τι να παρατηρήσεις",
  "How it works": "Πώς λειτουργεί",
  "Purpose": "Σκοπός",
  "Reading the output": "Ερμηνεία εξόδου",
  "Syntax": "Σύνταξη",
  "Example": "Παράδειγμα",
  "Caution": "Προσοχή",
  "Try in terminal": "Δοκίμασε στο τερματικό",
  "Review the concept, inspect the evidence, then run the command yourself.": "Ξαναδές τη θεωρία, εξέτασε τα στοιχεία και μετά δοκίμασε την εντολή.",
  "Hint": "Υπόδειξη",
  "Hide explanation": "Απόκρυψη εξήγησης",
  "Show explanation": "Εμφάνιση εξήγησης",
  "Checkpoint": "Σημείο ελέγχου",
  "Submit answers": "Υποβολή απαντήσεων",
  "Try again": "Δοκίμασε ξανά",
  "Your best score": "Καλύτερη επίδοση",
  "Correct": "Σωστό",
  "Review": "Δες ξανά",
  "question": "ερώτηση",
  "questions": "ερωτήσεις",
  "No quiz available": "Δεν υπάρχει διαθέσιμο κουίζ",
  "Learn the concepts first, then test your understanding with three quick questions.": "Μελέτησε πρώτα τις βασικές έννοιες και έλεγξε τις γνώσεις σου με τρεις σύντομες ερωτήσεις.",
  "All answers are checked on the server. Your best result is saved.": "Οι απαντήσεις ελέγχονται στον διακομιστή και αποθηκεύεται η καλύτερη επίδοσή σου.",
  "Excellent work!": "Εξαιρετική δουλειά!",
  "Keep practicing": "Συνέχισε την εξάσκηση",
  "Review the explanations below, then try again.": "Διάβασε τις εξηγήσεις παρακάτω και δοκίμασε ξανά.",
  "Concept": "Έννοια",
  "Evidence": "Τεκμήριο",
  "Practice": "Εξάσκηση",
  "Defender's view": "Από την πλευρά της άμυνας",
  "Try this": "Δοκίμασε αυτό",
  "Theory": "Θεωρία",
  "THE COMMUNITY / RANKINGS": "ΚΟΙΝΟΤΗΤΑ / ΚΑΤΑΤΑΞΗ",
  "The operator leaderboard": "Κατάταξη παικτών",
  "Every flag matters. Every lab counts. Earn your place among the best.": "Κάθε flag μετράει. Κάθε εργαστήριο σε βοηθά να προχωρήσεις. Κέρδισε τη θέση σου ανάμεσα στους καλύτερους.",
  "THE RACE NEVER STOPS": "Η ΠΡΟΣΠΑΘΕΙΑ ΔΕΝ ΣΤΑΜΑΤΑ ΠΟΤΕ",
  "Greatness is earned, not given.": "Η διάκριση κατακτιέται.",
  "Solve challenges, complete labs, and push past yesterday's version of yourself.": "Λύσε προκλήσεις, ολοκλήρωσε εργαστήρια και ξεπέρασε τον χθεσινό σου εαυτό.",
  "Earn more XP": "Κέρδισε περισσότερα XP",
  "The podium": "Το βάθρο",
  "The top minds in the arena right now.": "Οι κορυφαίοι παίκτες της αρένας αυτή τη στιγμή.",
  "YOUR STANDING": "Η ΘΕΣΗ ΣΟΥ ΣΤΗΝ ΚΑΤΑΤΑΞΗ",
  "How rankings work": "Πώς υπολογίζεται η κατάταξη",
  "Capture flags": "Βρες flags",
  "Finish labs": "Ολοκλήρωσε εργαστήρια",
  "Keep going": "Συνέχισε",
  "Climb the ranks": "Ανέβα στην κατάταξη",
  "THE COMMUNITY / LIVE FEED": "ΚΟΙΝΟΤΗΤΑ / ΖΩΝΤΑΝΗ ΡΟΗ",
  "The arena is alive": "Η αρένα είναι γεμάτη δράση",
  "Every solved puzzle and completed lab is another step forward.": "Κάθε γρίφος που λύνεις και κάθε εργαστήριο που ολοκληρώνεις σε φέρνει ένα βήμα πιο κοντά στον στόχο σου.",
  "LIVE ACTIVITY": "ΖΩΝΤΑΝΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ",
  "My activity": "Η δραστηριότητά μου",
  "All activity": "Όλη η δραστηριότητα",
  "Your momentum": "Η πρόοδός σου",
  "Labs completed": "Ολοκληρωμένα εργαστήρια",
  "View your profile": "Δες το προφίλ σου",
  "YOUR ACCOUNT / PROFILE": "ΛΟΓΑΡΙΑΣΜΟΣ / ΠΡΟΦΙΛ",
  "Your operator file": "Το προφίλ σου",
  "A record of where you've been and how far you've come.": "Δες την πορεία σου και όσα έχεις καταφέρει μέχρι τώρα.",
  "Achievements": "Επιτεύγματα",
  "Skill map": "Χάρτης δεξιοτήτων",
  "Recent milestones": "Πρόσφατα ορόσημα",
  "Saved missions": "Αποθηκευμένες αποστολές",
  "OPERATOR LEVEL": "ΕΠΙΠΕΔΟ ΠΑΙΚΤΗ",
  "Edit profile": "Επεξεργασία προφίλ",
  "Save changes": "Αποθήκευση αλλαγών",
  "Display name": "Εμφανιζόμενο όνομα",
  "Location": "Τοποθεσία",
  "About you": "Λίγα λόγια για σένα",
  "Guest operator": "Επισκέπτης",
  "Verified operator": "Επαληθευμένος λογαριασμός",
  "Total XP": "Συνολικά XP",
  "THE COMMUNITY / TEAM HUB": "ΚΟΙΝΟΤΗΤΑ / ΟΜΑΔΕΣ",
  "Stronger as a team": "Μαζί είμαστε πιο δυνατοί",
  "BETTER TOGETHER": "ΜΑΖΙ ΠΕΤΥΧΑΙΝΟΥΜΕ ΠΕΡΙΣΣΟΤΕΡΑ",
  "Find your people.": "Βρες την ομάδα σου.",
  "Capture more together.": "Περισσότερες νίκες, μαζί.",
  "Community crews": "Ομάδες της κοινότητας",
  "Have an invite code?": "Έχεις κωδικό πρόσκλησης;",
  "Build your own crew.": "Φτιάξε τη δική σου ομάδα.",
  "Create a team": "Δημιουργία ομάδας",
  "Join crew": "Γίνε μέλος της ομάδας",
  "YOUR CREW": "Η ΟΜΑΔΑ ΣΟΥ",
  "INVITE CODE": "ΚΩΔΙΚΟΣ ΠΡΟΣΚΛΗΣΗΣ",
  "CREW MEMBERS": "ΜΕΛΗ ΟΜΑΔΑΣ",
  "Leave team": "Αποχώρηση",
  "YOUR TEAM": "Η ΟΜΑΔΑ ΣΟΥ",
  "You are here": "Η θέση σου",
  "YOUR ACCOUNT / SETTINGS": "ΛΟΓΑΡΙΑΣΜΟΣ / ΡΥΘΜΙΣΕΙΣ",
  "Your public identity": "Η δημόσια ταυτότητά σου",
  "Safe by design.": "Ασφαλής σχεδιασμός από την αρχή.",
  "Keyboard shortcuts": "Συντομεύσεις πληκτρολογίου",
  "Guest access is active": "Η πρόσβαση επισκέπτη είναι ενεργή",
  "SUPPORT / FIELD MANUAL": "ΒΟΗΘΕΙΑ / ΟΔΗΓΟΣ ΧΡΗΣΗΣ",
  "Everything starts somewhere": "Κάθε αρχή γίνεται από κάπου",
  "Learn the rules. Break the puzzles.": "Μάθε τους κανόνες. Λύσε τους γρίφους.",
  "Frequently asked questions": "Συχνές ερωτήσεις",
  "The ethics promise": "Η δέσμευσή μας για υπεύθυνη εξάσκηση",
  "Capture a flag": "Βρες ένα flag",
  "Enter a lab": "Μπες σε εργαστήριο",
  "Find your crew": "Βρες την ομάδα σου",

};

export function translate(value: string, lang: Lang): string {
  return lang === "el" ? (GREEK_EXTRA[value] ?? GREEK_UI[value] ?? value) : value;
}
export function bi(value: Bi | string | undefined, lang: Lang): string {
  if (!value) return "";
  return typeof value === "string" ? translate(value, lang) : value[lang] || value.en;
}
