import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, BookOpen, Check, ChevronRight, Code2, Flag, KeyRound, LockKeyhole, ShieldCheck, Sparkles, Target, TerminalSquare, Trophy, UsersRound, Zap } from "lucide-react";
import { LanguageToggle, T } from "@/components/LanguageProvider";
import LandingTerminal from "@/components/LandingTerminal";
import { CHALLENGES } from "@/lib/challenges";
import { TOTAL_LABS } from "@/lib/platform";

export const metadata: Metadata = {
  title: "Gamehack — Learn cybersecurity by doing",
  description: "A safe, hands-on cyber range for curious minds. Practice ethical hacking with simulated challenges, guided labs, and an account that grows with you.",
};

const features = [
  { icon: Flag, tone: "lime", title: "Capture the flag", description: "Take on practical, story-driven challenges across web security, cryptography, OSINT, and digital forensics. Every solve teaches a technique, not just an answer." },
  { icon: BookOpen, tone: "violet", title: "Learn in the lab", description: "Follow structured paths from Linux and networking fundamentals to investigation and threat hunting, with interactive lessons and hands-on objectives." },
  { icon: Trophy, tone: "cyan", title: "See your progress", description: "Earn XP, build your operator profile, track streaks and skills, and compare your progress on a friendly community leaderboard." },
];

const steps = [
  { number: "01", icon: Target, title: "Pick a mission", description: "Choose a guided challenge or follow a learning path at your own pace." },
  { number: "02", icon: TerminalSquare, title: "Explore safely", description: "Use Gamehack’s simulated tools and fictional targets. Your practice stays inside the range." },
  { number: "03", icon: Sparkles, title: "Grow your skills", description: "Solve objectives, earn XP, and make your progress part of your operator story." },
];

export default function HomePage() {
  return <main className="landing-page">
    <header className="landing-nav"><div className="landing-nav-inner"><Link href="/" className="landing-brand" aria-label="Gamehack home"><span className="landing-brand-mark"><Zap size={21} fill="currentColor" /></span><span><span className="landing-brand-name">GAME<span>HACK</span></span><span className="landing-brand-sub"><T en="CYBER RANGE" el="ΕΚΠΑΙΔΕΥΤΙΚΟ CYBER RANGE" /></span></span></Link><nav className="landing-nav-links" aria-label="Main navigation"><a href="#range"><T en="The range" el="Η πλατφόρμα" /></a><a href="#how-it-works"><T en="How it works" el="Πώς λειτουργεί" /></a><a href="#safety"><T en="Safety" el="Ασφάλεια" /></a></nav><div className="landing-nav-actions"><LanguageToggle compact /><Link href="/login" className="landing-signin"><T en="Sign in" el="Σύνδεση" /></Link><Link href="/register" className="btn-primary !min-h-[38px] !px-3.5"><T en="Join free" el="Δωρεάν εγγραφή" /><ArrowRight size={14} /></Link></div></div></header>

    <section className="landing-hero"><div className="landing-hero-glow" /><div className="landing-hero-grid"><div className="landing-hero-copy"><div className="landing-eyebrow"><span className="landing-eyebrow-dot" /><T en="A HANDS-ON CYBER RANGE FOR CURIOUS MINDS" el="ΠΡΑΚΤΙΚΗ ΕΚΠΑΙΔΕΥΣΗ CYBER ΓΙΑ ΑΝΗΣΥΧΑ ΜΥΑΛΑ" /></div><h1 className="landing-title"><T en="Think like a hacker." el="Σκέψου σαν hacker." /><br /><em><T en="Train like a pro." el="Εκπαιδεύσου σαν επαγγελματίας." /></em></h1><p className="landing-lede"><T en="Build real cybersecurity instincts by doing the work. Solve story-driven challenges, explore guided labs, and grow your skills in a safe range built for practice." el="Ανάπτυξε πραγματικές δεξιότητες κυβερνοασφάλειας μέσα από την πράξη. Λύσε προκλήσεις, εξερεύνησε καθοδηγούμενα labs και προχώρησε με ασφάλεια." /></p><div className="landing-hero-actions"><Link href="/register" className="btn-primary landing-primary-cta"><Zap size={16} fill="currentColor" /><T en="Create your free account" el="Δημιούργησε δωρεάν λογαριασμό" /><ArrowRight size={15} /></Link><a href="#range" className="landing-secondary-cta"><span className="landing-play-icon">⌄</span><T en="Explore the platform" el="Εξερεύνησε την πλατφόρμα" /></a></div><div className="landing-promises"><span><Check size={13} /><T en="No email required" el="Χωρίς email" /></span><span><Check size={13} /><T en="Practice safely" el="Ασφαλής εξάσκηση" /></span><span><Check size={13} /><T en="Keep your progress" el="Διατήρησε την πρόοδό σου" /></span></div></div><div className="landing-hero-visual"><div className="landing-visual-orbit landing-orbit-one" /><div className="landing-visual-orbit landing-orbit-two" /><div className="landing-visual-label"><span className="status-dot" /><span><T en="TRAINING RANGE ONLINE" el="ΤΟ CYBER RANGE ΕΙΝΑΙ ΕΝΕΡΓΟ" /></span></div><LandingTerminal /><div className="landing-visual-caption"><LockKeyhole size={12} /><span><T en="Fictional targets. Simulated commands. Real learning." el="Εικονικοί στόχοι. Προσομοιωμένες εντολές. Πραγματική γνώση." /></span></div></div></div><a className="landing-scroll-cue" href="#range"><span><T en="DISCOVER GAMEHACK" el="ΑΝΑΚΑΛΥΨΕ ΤΟ GAMEHACK" /></span><ArrowDown size={13} /></a></section>

    <section className="landing-proof-strip" aria-label="Gamehack at a glance"><div className="landing-proof-inner"><div><strong>{CHALLENGES.length}<span>+</span></strong><span><T en="interactive challenges" el="διαδραστικές προκλήσεις" /></span></div><div><strong>{TOTAL_LABS}<span>+</span></strong><span><T en="guided lab modules" el="καθοδηγούμενα lab modules" /></span></div><div><strong>0</strong><span><T en="real systems in scope" el="πραγματικά συστήματα στο πεδίο" /></span></div><div className="landing-proof-note"><ShieldCheck size={19} /><span><strong><T en="Practice with purpose." el="Εξασκήσου με σκοπό." /></strong><small><T en="Learn ethically, one safe challenge at a time." el="Μάθε ηθικά, μία ασφαλής πρόκληση τη φορά." /></small></span></div></div></section>

    <section id="range" className="landing-section landing-range-section"><div className="landing-section-heading"><div><div className="landing-section-eyebrow"><T en="THE GAMEHACK RANGE" el="ΤΟ CYBER RANGE GAMEHACK" /></div><h2><T en="A real place to practice." el="Ένας χώρος για να εξασκηθείς." /></h2></div><p><T en="Not another wall of theory. Gamehack gives you a safe space to explore, experiment, and learn by doing." el="Όχι άλλη μία θεωρία. Το Gamehack σου δίνει έναν ασφαλή χώρο για να εξερευνήσεις και να μάθεις μέσα από την πράξη." /></p></div><div className="landing-feature-grid">{features.map(({ icon: Icon, tone, title, description }, index) => <article className={`landing-feature-card tone-${tone}`} key={title}><span className="landing-feature-index">0{index + 1}</span><span className="landing-feature-icon"><Icon size={21} /></span><h3><T en={title} el={index === 0 ? "Κατάκτησε το flag" : index === 1 ? "Μάθε στο εργαστήριο" : "Παρακολούθησε την πρόοδό σου"} /></h3><p><T en={description} el={index === 0 ? "Αναμετρήσου με πρακτικές προκλήσεις σε web security, κρυπτογραφία, OSINT και ψηφιακή εγκληματολογική έρευνα. Κάθε λύση διδάσκει μια τεχνική." : index === 1 ? "Ακολούθησε δομημένες διαδρομές από τα βασικά του Linux και των δικτύων έως την έρευνα, με διαδραστικά μαθήματα και πρακτικούς στόχους." : "Κέρδισε XP, δημιούργησε το προφίλ σου, παρακολούθησε streaks και δεξιότητες, και σύγκρινε την πρόοδό σου με την κοινότητα."} /></p><Link href={index === 1 ? "/academy" : "/challenges"} className="landing-card-link"><T en={index === 1 ? "Explore learning paths" : "Explore challenges"} el={index === 1 ? "Εξερεύνησε τις διαδρομές" : "Εξερεύνησε τις προκλήσεις"} /><ChevronRight size={14} /></Link></article>)}</div></section>

    <section id="how-it-works" className="landing-how-section"><div className="landing-how-inner"><div className="landing-how-intro"><div className="landing-section-eyebrow"><T en="YOUR NEXT CHAPTER" el="ΤΟ ΕΠΟΜΕΝΟ ΒΗΜΑ ΣΟΥ" /></div><h2><T en="Start curious.\nLeave more capable." el="Ξεκίνα από περιέργεια.\nΠροχώρα με νέες δεξιότητες." /></h2><p><T en="Whether you're brand new to cybersecurity or sharpening skills you already have, there's a clear next step waiting for you." el="Είτε ξεκινάς τώρα είτε εξελίσσεις τις γνώσεις σου, υπάρχει πάντα ένα επόμενο βήμα." /></p><Link className="landing-inline-link" href="/register"><T en="Build your operator profile" el="Δημιούργησε το προφίλ σου" /><ArrowRight size={14} /></Link></div><div className="landing-steps">{steps.map(({ number, icon: Icon, title, description }) => <article key={number} className="landing-step"><span className="landing-step-number">{number}</span><span className="landing-step-icon"><Icon size={17} /></span><div><h3><T en={title} el={number === "01" ? "Διάλεξε αποστολή" : number === "02" ? "Εξερεύνησε με ασφάλεια" : "Ανάπτυξε τις δεξιότητές σου"} /></h3><p><T en={description} el={number === "01" ? "Επίλεξε μια καθοδηγούμενη πρόκληση ή ακολούθησε μια μαθησιακή διαδρομή με τον δικό σου ρυθμό." : number === "02" ? "Χρησιμοποίησε τα προσομοιωμένα εργαλεία και τους εικονικούς στόχους του Gamehack." : "Λύσε στόχους, κέρδισε XP και χτίσε την ιστορία σου ως operator."} /></p></div></article>)}</div></div></section>

    <section id="safety" className="landing-safety-section"><div className="landing-safety-card"><div className="landing-safety-art"><div className="landing-safety-rings"><span /><span /><span /><i><ShieldCheck size={28} /></i></div><div className="landing-safety-tag"><span className="status-dot" /><T en="SIMULATED ENVIRONMENT" el="ΠΡΟΣΟΜΟΙΩΜΕΝΟ ΠΕΡΙΒΑΛΛΟΝ" /></div></div><div className="landing-safety-copy"><div className="landing-section-eyebrow"><T en="ETHICS BUILT IN" el="Η ΗΘΙΚΗ ΕΙΝΑΙ ΒΑΣΙΚΗ ΑΡΧΗ" /></div><h2><T en="Learn the craft. Respect the boundary." el="Μάθε την τέχνη. Σεβάσου τα όρια." /></h2><p><T en="Every exercise is designed for a fictional, controlled environment. The CLI above is a local simulation; its commands don't run on your device, touch the internet, or scan real systems." el="Κάθε άσκηση είναι σχεδιασμένη για ένα εικονικό, ελεγχόμενο περιβάλλον. Το CLI παραπάνω είναι προσομοίωση: οι εντολές δεν εκτελούνται στη συσκευή σου, δεν συνδέονται στο διαδίκτυο και δεν σαρώνουν πραγματικά συστήματα." /></p><ul><li><Check size={15} /><span><T en="Fictional filesystems and targets" el="Εικονικά συστήματα αρχείων και στόχοι" /></span></li><li><Check size={15} /><span><T en="Commands are explicitly simulated" el="Οι εντολές είναι προσομοιωμένες" /></span></li><li><Check size={15} /><span><T en="Practice ethical, responsible security" el="Υπεύθυνη και ηθική εξάσκηση στην ασφάλεια" /></span></li></ul></div></div></section>

    <section className="landing-final-cta"><div className="landing-final-glow" /><div className="landing-final-copy"><span className="landing-final-mark"><Code2 size={22} /></span><div><div className="landing-section-eyebrow"><T en="THE NEXT FLAG IS YOURS" el="ΤΟ ΕΠΟΜΕΝΟ FLAG ΕΙΝΑΙ ΔΙΚΟ ΣΟΥ" /></div><h2><T en="Your first mission starts here." el="Η πρώτη σου αποστολή ξεκινά εδώ." /></h2><p><T en="Create an account in under a minute. No email required—just your handle, a password, and your private recovery key file." el="Δημιούργησε λογαριασμό σε λιγότερο από ένα λεπτό. Δεν χρειάζεται email—μόνο όνομα χρήστη, κωδικός και το ιδιωτικό αρχείο ανάκτησης." /></p><div className="landing-final-actions"><Link href="/register" className="btn-primary"><T en="Join Gamehack free" el="Γίνε μέλος του Gamehack δωρεάν" /><ArrowRight size={14} /></Link><Link href="/dashboard" className="landing-guest-link"><UsersRound size={14} /><T en="Explore as a guest" el="Εξερεύνησε ως επισκέπτης" /></Link></div></div></div><div className="landing-final-side"><div><KeyRound size={15} /><span><T en="Private recovery key" el="Ιδιωτικό κλειδί ανάκτησης" /></span></div><div><LockKeyhole size={15} /><span><T en="No email needed" el="Δεν απαιτείται email" /></span></div><div><ShieldCheck size={15} /><span><T en="Safe by design" el="Ασφαλές από σχεδιασμό" /></span></div></div></section>

    <footer className="landing-footer"><Link href="/" className="landing-footer-brand">GAME<span>HACK</span></Link><span>© {new Date().getFullYear()} GAMEHACK · <T en="Train ethically. Think differently." el="Εξασκήσου ηθικά. Σκέψου διαφορετικά." /></span><div><Link href="/login"><T en="Sign in" el="Σύνδεση" /></Link><Link href="/help"><T en="Help & support" el="Βοήθεια" /></Link></div></footer>
  </main>;
}
