"use client";


import { T } from "@/components/LanguageProvider";
import Link from "next/link";
import { ArrowRight, Crown, Flag, Medal, ShieldCheck, Trophy, Zap } from "lucide-react";
import { Avatar, ProgressBar } from "@/components/ui";
import { useProgress } from "@/components/ProgressProvider";
import { operatorTitle } from "@/lib/progress";
import type { LeaderboardEntry } from "@/lib/platform";

export default function LeaderboardView({ initialEntries }: { initialEntries: LeaderboardEntry[] }) {
  const progress = useProgress();
  const own: LeaderboardEntry = {
    id: progress.player.id,
    handle: progress.player.handle,
    displayName: progress.player.displayName,
    xp: progress.xp,
    solves: progress.solves.length,
    avatar: "#c5f277",
    isYou: true,
  };
  const entries = [...initialEntries.filter(entry => !entry.isYou), own].sort((a, b) => b.xp - a.xp).map((entry, index) => ({ ...entry, rank: index + 1 }));
  const current = entries.find(entry => entry.isYou)!;
  const above = entries.find(entry => entry.rank === current.rank - 1);
  const gap = above ? above.xp - progress.xp : 0;

  return <><section><div className="mb-4 flex items-center justify-between"><div><h2 className="display-font text-[20px] font-bold"><T>The podium</T></h2><p className="mt-1 text-[11px] text-[#8b9ba6]"><T>The top minds in the arena right now.</T></p></div><span className="text-[10px] text-[#8595a1]">{entries.length} <T>ranked operators</T></span></div><div className="grid gap-4 md:grid-cols-3">{[entries[1], entries[0], entries[2]].map(entry => { const first = entry.rank === 1; const color = first ? "#e9cc86" : entry.rank === 2 ? "#c4d2d8" : "#d2aa8d"; return <div key={entry.id} className={`panel relative overflow-hidden p-6 text-center ${first ? "border-[#6d6346] bg-[radial-gradient(circle_at_50%_0%,rgba(232,203,131,.12),transparent_65%),#191e25]" : ""}`}><div className="absolute right-3 top-3 mono text-[10px] text-[#657684]">#{String(entry.rank).padStart(2, "0")}</div><div className="mx-auto mb-4 grid h-[58px] w-[58px] place-items-center rounded-2xl border" style={{ borderColor: `${color}55`, background: `${color}14`, color }}>{first ? <Crown size={26} /> : <Medal size={25} />}</div><div className="flex justify-center"><Avatar name={entry.displayName} color={entry.avatar} /></div><h3 className="display-font mt-3 text-[17px] font-bold">{entry.displayName}</h3><p className="mt-1 text-[10px] text-[#8a9ca4]">@{entry.handle}</p><div className="mt-4 border-t border-[#303a43] pt-4"><strong className="display-font text-[22px] font-bold" style={{ color }}>{entry.xp.toLocaleString()}</strong><span className="ml-1 text-[10px] font-bold text-[#8e9ea7]">XP</span><p className="mt-1 text-[10px] text-[#8c9da6]">{entry.solves} <T>flags captured</T></p></div></div>; })}</div></section>
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1.78fr)_minmax(285px,1fr)]"><section><div className="mb-4"><h2 className="display-font text-[20px] font-bold"><T>Full rankings</T></h2><p className="mt-1 text-[11px] text-[#8b9ba6]"><T>A little competition makes everyone better.</T></p></div><div className="panel overflow-hidden"><div className="grid grid-cols-[45px_minmax(0,1fr)_62px_78px] gap-2 border-b border-[#303a43] px-4 py-3 text-[9px] font-bold tracking-[.13em] text-[#80909d] sm:grid-cols-[55px_minmax(0,1fr)_100px_120px]"><span><T>RANK</T></span><span><T>OPERATOR</T></span><span className="text-right"><T>FLAGS</T></span><span className="text-right"><T>TOTAL XP</T></span></div>{entries.map(entry => <div key={entry.id} className={`grid grid-cols-[45px_minmax(0,1fr)_62px_78px] items-center gap-2 border-b border-[#29333d] px-4 py-3 last:border-0 sm:grid-cols-[55px_minmax(0,1fr)_100px_120px] ${entry.isYou ? "bg-[#26372b]" : "hover:bg-[#1c2530]"}`}><span className={`display-font text-[13px] font-bold ${entry.isYou ? "text-lime" : entry.rank === 1 ? "text-[#dfc47e]" : "text-[#9aabb3]"}`}>{String(entry.rank).padStart(2, "0")}</span><div className="flex min-w-0 items-center gap-2.5"><Avatar name={entry.displayName} color={entry.avatar} size="sm" /><div className="min-w-0"><strong className={`block truncate text-[11px] ${entry.isYou ? "text-lime" : "text-[#e5ece9]"}`}>{entry.displayName} {entry.isYou && <span className="ml-1 rounded bg-[#435e37] px-1.5 py-0.5 text-[8px]"><T>YOU</T></span>}</strong><span className="block truncate text-[9px] text-[#81929e]">@{entry.handle}</span></div></div><span className="text-right mono text-[11px] text-[#a6b5bc]">{entry.solves}</span><strong className={`text-right mono text-[11px] ${entry.isYou ? "text-lime" : "text-[#e4ece9]"}`}>{entry.xp.toLocaleString()}</strong></div>)}</div></section>
      <div className="space-y-5"><section className="panel overflow-hidden"><div className="border-b border-[#334039] bg-[#202e25] p-5"><span className="text-[10px] font-bold tracking-[.13em] text-lime"><T>YOUR STANDING</T></span><div className="mt-4 flex items-center gap-3"><Avatar name={progress.player.displayName} size="lg" /><div><strong className="display-font block text-[18px] font-bold">{progress.player.displayName}</strong><span className="text-[10px] text-[#9bae9d]">{operatorTitle(progress.xp)}</span></div></div></div><div className="p-5"><div className="flex items-end justify-between"><div><span className="text-[10px] text-[#96a6ac]"><T>Global rank</T></span><strong className="display-font mt-1 block text-[29px] font-bold text-lime">#{String(current.rank).padStart(2, "0")}</strong></div><div className="text-right"><span className="text-[10px] text-[#96a6ac]"><T>Total XP</T></span><strong className="display-font mt-1 block text-[21px] font-bold">{progress.xp.toLocaleString()}</strong></div></div>{above && <div className="mt-5"><div className="mb-2 flex justify-between text-[10px]"><span className="text-[#91a0a8]"><T>To rank #</T>{above.rank}</span><strong className="text-lime">{gap.toLocaleString()} XP to go</strong></div><ProgressBar percent={Math.max(4, Math.round(progress.xp / above.xp * 100))} /></div>}<Link href="/challenges" className="btn-primary mt-5 w-full"><T>Climb the ranks</T> <ArrowRight size={14} /></Link></div></section><section className="panel p-5"><div className="flex items-center gap-2"><ShieldCheck size={17} className="text-lime" /><h3 className="display-font text-[15px] font-bold"><T>How rankings work</T></h3></div><div className="mt-4 space-y-3"><div className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded bg-[#304330] text-lime"><Flag size={13} /></span><div><strong className="text-[11px]"><T>Capture flags</T></strong><p className="text-[10px] leading-relaxed text-[#8f9fa7]"><T>Each challenge awards its listed XP once.</T></p></div></div><div className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded bg-[#304330] text-lime"><Zap size={13} /></span><div><strong className="text-[11px]"><T>Finish labs</T></strong><p className="text-[10px] leading-relaxed text-[#8f9fa7]"><T>Verified objectives earn XP as you train.</T></p></div></div><div className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded bg-[#304330] text-lime"><Trophy size={13} /></span><div><strong className="text-[11px]"><T>Keep going</T></strong><p className="text-[10px] leading-relaxed text-[#8f9fa7]"><T>Your cumulative XP determines your place.</T></p></div></div></div></section></div></div>
  </>;
}
