import { T } from "@/components/LanguageProvider";
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CircleHelp, Database, KeyRound, LockKeyhole, ShieldCheck, TerminalSquare } from "lucide-react";
import AccountPanel from "@/components/AccountPanel";
import SettingsIdentity from "@/components/SettingsIdentity";

export const metadata: Metadata = { title: "Settings", description: "Manage your Gamehack operator account." };
export const dynamic = "force-dynamic";

export default function SettingsPage() {
  return <div className="space-y-7"><div><div className="page-eyebrow"><T>YOUR ACCOUNT / SETTINGS</T></div><h1 className="page-title"><T>Account settings</T><span className="text-lime">.</span></h1><p className="page-description"><T>Manage your identity and understand how your training data is handled.</T></p></div><div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(300px,1fr)]"><div className="space-y-6"><AccountPanel /><SettingsIdentity /></div><div className="space-y-5"><section className="panel p-5"><span className="grid h-10 w-10 place-items-center rounded-lg bg-[#2b422f] text-lime"><ShieldCheck size={20} /></span><h3 className="display-font mt-4 text-[17px] font-bold"><T>Safe by design.</T></h3><p className="mt-2 text-[11px] leading-relaxed text-[#96a7ac]"><T>Gamehack&apos;s terminal runs against a fictional virtual filesystem. Commands never touch the server&apos;s operating system or any real target.</T></p><div className="mt-5 space-y-3 border-t border-[#2f3e3d] pt-4"><div className="flex items-center gap-2 text-[10px] text-[#b0c0b5]"><TerminalSquare size={14} className="text-lime" /> <T>Isolated simulated labs</T></div><div className="flex items-center gap-2 text-[10px] text-[#b0c0b5]"><Database size={14} className="text-lime" /> <T>Progress saved in PostgreSQL</T></div><div className="flex items-center gap-2 text-[10px] text-[#b0c0b5]"><LockKeyhole size={14} className="text-lime" /> <T>Secure, private account sessions</T></div></div></section><section className="panel p-5"><div className="flex items-center gap-2"><KeyRound size={17} className="text-violet" /><h3 className="display-font text-[16px] font-bold"><T>Keyboard shortcuts</T></h3></div><div className="mt-4 flex items-center justify-between border-b border-[#2e3942] py-2.5 text-[11px]"><span className="text-[#9aaab1]"><T>Quick search</T></span><kbd className="rounded border border-[#46515a] bg-[#263039] px-2 py-1 mono text-[10px]">⌘ K / Ctrl K</kbd></div><div className="flex items-center justify-between py-2.5 text-[11px]"><span className="text-[#9aaab1]"><T>Find a mission</T></span><kbd className="rounded border border-[#46515a] bg-[#263039] px-2 py-1 mono text-[10px]">/</kbd></div></section><Link href="/help" className="panel flex items-center gap-3 p-4 hover:border-[#5a7053]"><CircleHelp size={19} className="text-lime" /><span className="flex-1 text-[11px] font-semibold"><T>Need help getting started?</T></span><ArrowRight size={14} className="text-lime" /></Link></div></div></div>;
}
